### ISSUE TITLE
Provide update_manifest script which would make updates efficient

### ISSUE THREAD

**Issue by yarikoptic** [dandi/zarr-manifests#3]
We are using `s3_client.get_paginator('list_object_versions')` S3 call to get through all the versions of all the keys in the prefix:
https://github.com/dandi/zarr-manifests/blob/master/list_bucket_prefix_versionids.py#L59 . In case of checking for  updates it would be **very inefficient** for zarrs since would require first to list all prior versions/keys.

chatgpt suggested that it might be possible to make it efficient if for each prefix we would remember not only the latest last-modified datestamp which allows us to "cut-off" to say if there are new changes, but also to store the pagination marker

<details>
<summary>prototypical schematic code chatgpt offered</summary> 

```shell
import boto3

s3 = boto3.client('s3')
bucket_name = 'your-bucket-name'
prefix = 'your-prefix/'

# Start with no markers
key_marker = None
version_id_marker = None

while True:
    response = s3.list_object_versions(
        Bucket=bucket_name,
        Prefix=prefix,
        KeyMarker=key_marker if key_marker else '',
        VersionIdMarker=version_id_marker if version_id_marker else ''
    )

    # Process your versions and delete markers here
    # for version in response.get('Versions', []):
    #     process_version(version)
    # for delete_marker in response.get('DeleteMarkers', []):
    #     process_delete_marker(delete_marker)

    # Check if there's more data to process
    if response['IsTruncated']:
        key_marker = response.get('NextKeyMarker')
        version_id_marker = response.get('NextVersionIdMarker')
    else:
        break

```
</details>

and indeed  https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectVersions.html#API_ListObjectVersions_RequestSyntax lists

![image](https://github.com/dandi/zarr-manifests/assets/39889/a14bcf3a-696a-470f-97e8-f761859f73ba)

so we "officially" can start listing from some versionid marker, and thus to establish efficient update of the manifest listing by processing DeleteMarkers and overwrites for existing Keys.

Current scripts in this repo do manifest preparation in two stages:
- https://github.com/dandi/zarr-manifests/blob/master/list_bucket_prefix_versionids.py -- lists an original flat list of keys
- https://github.com/dandi/zarr-manifests/blob/master/convert_schema_1to2.py - converts it to that tree-like structure with summary record ontop which is what we have in this git-annex repo under https://github.com/dandi/zarr-manifests/tree/master/zarr-manifests-v2-sorted and looking like
```json
{
 "schemaVersion": 2,
 "fields": ["versionId","lastModified","size","ETag"],
 "statistics": {
  "entries": 12627,
  "depth": 3,
  "totalSize": 17349834562,
  "lastModified": "2023-11-24T22:01:13+00:00",
  "zarrChecksum": "d987dab7f35d23ae348e8425e018d6a2-12627--17349834562"
 },
 "entries": {
  ".zattrs": ["J1G4_YuxaSxsSamUUQCU_xSG58W7.E30","2023-11-24T21:06:26+00:00",2879,"761f9d90aa42cf59c4f248d962421ae4"],
  ".zgroup": ["yCpoxZ3L5rA50FCxQdDfjJRCuiUcpEPh","2023-11-24T21:06:27+00:00",24,"e20297935e73dd0154104d4ea53040ab"],
  "0": {
   ".zarray": ["wscCsBsjmNhP825JBXxJkrSnA4eNZkCW","2023-11-24T21:06:26+00:00",399,"b2411e9a575526c3f188cf656926e35e"],
   "0": {
    "0": {
...
```

so, in addition to '"statistics"' we can store the `versionIdMarker` which we can then use for subsequent efficient `list_object_versions`.

I think the solution, script `update_manifest` should 
- merge those two scripts (no longer need to separate) and produce this new `schemaVersion: 3` (with `versionIdMarker`) file
- have a mode of operation (similar to how we have in dandi2backup) `--mode incremental,check,force` where in `incremental` it would make use of `versionIdMarker` and in `force` would go from the beginning; 'check' -- just check if anything new, and report back "changes present" or "changes absent" without producing updated manifest.
- I do not think we need that slim 'versionid.json' version of the manifest file as produced now  
- ATM I encoded cases when checksum differs from what is in dandiarchive DB: https://github.com/dandi/zarr-manifests/blob/master/convert_schema_1to2.py#L153 . We should make it separate field, e.g. `zarrChecksumMismatch` which would be present only if mismatches and contain the mismatched one (typically `null` as per https://github.com/dandi/dandi-archive/issues/1842)

`update_manifest` script should probably have following interface overall

```
update_manifest [--s3-prefix PREFIX (default: s3://dandiarchive/zarr)] [--mode incremental,check,force] --manifests-root PATH zarr_id
```

so regular cron job would be going through zarr_ids and  invoke `update_manifest --manifests-root zarr-manifests-v2-sorted ZARR_ID` to get them possibly updated efficiently.

For a given zarr_id, it would first need to find the most recent (according to lastModified) present version of the manifest (if any) in the `manifests-root`, get is versionIdMarker and proceed from there. Or proceed from the beginning if there is no version.

**Comment by jwodder** [comment]
@yarikoptic 

> In case of checking for updates it would be very inefficient for zarrs since would require first to list all prior versions/keys.

What do you mean by "prior versions/keys"?  `list_object_versions` returns versions sorted from newest to oldest ([ref](https://repost.aws/questions/QUKgTEMH3dQlGBfsxYYYmldA/is-it-safe-to-rely-on-versions-ordering-in-listobjectversions-response)), so the versions listed first are the most recent.

**Comment by yarikoptic** [comment]
ha -- we are both right kinda ;)  the reference you provide has answer

> The second example in the documentation states that objects are returned in the order they are stored: https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectVersions.html#API_ListObjectVersions_Examples

but what I assumed was that "object" is here a combination of key+version.  Apparently it is not -- it is just a "key", and then per each key we get all version in the order from newest to oldest it seems. With the following patch

```patch
❯ git diff
diff --git a/list_bucket_prefix_versionids.py b/list_bucket_prefix_versionids.py
index 0eade873a..1316785d8 100755
--- a/list_bucket_prefix_versionids.py
+++ b/list_bucket_prefix_versionids.py
@@ -62,6 +62,8 @@ def list_versions(bucket_name, prefix, before_last_modified=None):
         if 'Versions' in page:
             for version in page['Versions']:
                 last_modified = version['LastModified']
+                key = version['Key'][len(prefix):].lstrip('/')
+                print('XXX', last_modified, key)
                 if before_last_modified and last_modified > before_last_modified:
                     continue
                 key = version['Key'][len(prefix):].lstrip('/')
```

we get

```
❯ python list_bucket_prefix_versionids.py s3://dandiarchive/zarr/7723d02f-1f71-4553-a7b0-47bda1ae8b42/ | head
XXX 2022-05-09 10:46:23+00:00 .zattrs
XXX 2022-05-09 00:59:19+00:00 .zattrs
XXX 2022-05-09 00:59:19+00:00 .zgroup
XXX 2022-05-09 13:38:46+00:00 .zmetadata
XXX 2022-05-09 10:47:05+00:00 .zmetadata
XXX 2022-05-09 13:38:44+00:00 0/.zarray
XXX 2022-05-09 10:46:54+00:00 0/.zarray
XXX 2022-05-09 00:59:19+00:00 0/.zarray
XXX 2022-05-09 10:46:22+00:00 0/.zattrs
XXX 2022-05-09 09:55:10+00:00 0/.zattrs
Traceback (most recent call last):
  File "/home/yoh/proj/dandi/zarr-manifests/list_bucket_prefix_versionids.py", line 119, in <module>
    versions = list_versions(bucket_name, prefix)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoh/proj/dandi/zarr-manifests/list_bucket_prefix_versionids.py", line 66, in list_versions
    print('XXX', last_modified, key)
BrokenPipeError: [Errno 32] Broken pipe
❯ python list_bucket_prefix_versionids.py s3://dandiarchive/zarr/7723d02f-1f71-4553-a7b0-47bda1ae8b42/ | grep XXX | tail
XXX 2022-05-09 09:43:26+00:00 4/0/0/1/1/3
XXX 2022-05-09 01:00:50+00:00 4/0/0/1/1/3
XXX 2022-05-09 09:43:26+00:00 4/0/0/1/2/0
XXX 2022-05-09 01:00:50+00:00 4/0/0/1/2/0
XXX 2022-05-09 09:43:26+00:00 4/0/0/1/2/1
XXX 2022-05-09 01:00:50+00:00 4/0/0/1/2/1
XXX 2022-05-09 09:43:26+00:00 4/0/0/1/2/2
XXX 2022-05-09 01:00:50+00:00 4/0/0/1/2/2
XXX 2022-05-09 09:43:26+00:00 4/0/0/1/2/3
XXX 2022-05-09 01:00:50+00:00 4/0/0/1/2/3
```

so the `.zattrs` was originally added first (at 00:59:19+00:00) and hence listed first, but then its versions go from most recent to the oldest.

- Overall -- we are still listing all the versions of all the keys which is not desired/needed.  
- If the newest updated key is the last added originally -- it would be listed last.
- By providing some magical `versionIdMarker` I hope we could avoid listing all keys/versions

**Comment by jwodder** [comment]
@yarikoptic So what exactly is the overall desired behavior for the script?  Should it just fetch the current state of the given Zarr?  Then exactly what role is the versioning information supposed to play?  It is just to easily detect whether the Zarr has changed since its manifest was last calculated?  Or does fetching information for all the entries in a Zarr take too long, and you're looking for a way to only fetch information for the ones that have changed?

**Comment by yarikoptic** [comment]
"versioning information" is ambiguous in this context to answer quickly - could refer to versionIds in URLs or that versionIdMarker for the listing... but I think the last question is nailing it:  currently it would take too long to (re)fetch all information (IIRC it took almost a week to get a full set of zarr manifests originally).  If we could fetch only "what has changed" and use it on top of previously fetched manifest - I think this would make it feasible to quickly check/update all zarr manifests.

**Comment by jwodder** [comment]
@yarikoptic It appears that the `version-id-marker` parameter is just for pagination (See the documentation for the `IsTruncated`, `NextKeyMarker`, and `NextVersionIdMarker` response fields in [the ListObjectVersions docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectVersions.html#API_ListObjectVersions_ResponseElements)).  Thus, if you save a version ID and reuse it in a later request, the response will just be the object versions that come after that point in the full listing for the prefix.  There doesn't seem to be a way to ask the server for only those objects created/modified after a certain point in time.

**Comment by yarikoptic** [comment]
eh, no perfection in this world... ok, then changing the plan to
- stay with `"schemaVersion": 2,` i.e. no magic to be added
- `--mode api-check,force`. api-check - would compare zarr-checksum against the one provided by our API. If API has none, do nothing; if API has different one: run update; if API has the same: do nothing.  In 'force' : do update regardless.

**Comment by jwodder** [comment]
@yarikoptic 

> api-check - would compare zarr-checksum against the one provided by our API.

The presence of the `--s3-prefix` option in the usage summary in the top comment implies that you want to be able to run this script against Zarrs in staging as well as production, which means that both the S3 prefix and API URL will have to vary in lockstep.  Wouldn't it be better for the script to take a `--dandi-instance <dandi|dandi-staging>` option instead of `--s3-prefix`, with the script then mapping the instance name to the appropriate S3 prefix and API URL?

**Comment by yarikoptic** [comment]
Agree.
