### ISSUE TITLE
If no zarr_id is provided -- loop through all zarrs in the bucket + fetch all zarrs from API server "at once"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/zarr-manifests#6]
I do not really care about run time, but currently we are bombarding the api server a little too much unnecessarily since we are inquiring checksum per each zarr looping through all zarrs in the bucket in https://github.com/dandi/zarr-manifests/blob/master/get_them_all.sh .

Let's, if no zar_id specified
- hit `{instance.api}/zarr/` end point and get all zarrs known to the instance
- loop through all of them (instead of listing S3 bucket explicitly) while also using already known zarr checksum

This way we would have only handful paginated requests to `/zarr/` and I expect update going on really fast in case of no changes so we could make it run more frequently.

**Comment by jwodder** [comment]
@yarikoptic To be clear: This is something you want implemented solely in `update_manifest.py`, without touching `get_them_all.sh`, correct?

**Comment by yarikoptic** [comment]
yes, so we have a single python process to take advantage  of it.
